### ISSUE TITLE
Filter page results from category queries on the backend

### ISSUE THREAD

**Issue by wandaczerwinski** [HindsightTwentyTwenty/backend#80]
Right now I'm doing some very ugly nested forloops on the frontend categories page to return the sites the user has labeled as certain categories. If I'm querying for both 'cats' and 'dogs' and a user has marked 'zootopia' with both these tags, the page is returned twice. It'd be nice if this filtering was done on the backend somehow and each page was only returned once.

**Comment by zatannenbaum** [comment]
@wandaczerwinski Right now when you get to this page you send me a request for all of the categories and all of their associated pages and it all gets returned at once. In order for this to not be the case you would need to send me a request with the categories you want every time the categories change

**Comment by wandaczerwinski** [comment]
@zatannenbaum Ah gotcha. So could you make a new endpoint where I would just send you a short list of only the search categories? That'd be super easy for me; I already made search categories a part of the store.

**Comment by zatannenbaum** [comment]
@wandaczerwinski I don't think this is a good idea because it would cause a noticeable delay in the user experience. It shouldn't be terribly hard front end logic. Can you combine lists of pages and then change the object type to be a set so that it removes the duplicates for you?
